### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by NicoGonzalez94** [JoaqAb/rc-finalproject-resto-fe#25]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Encontrar un logo al lado del nombre.

## Resultado actual

• Se encuentra el nombre, pero no el logo.

## Captura

![image](https://github.com/JoaqAb/rc-finalproject-resto-fe/assets/166792979/084ba3ad-0559-4a74-bde6-1e166d80f831)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by ramirokhouri** [comment]
resuelto el issue de la imagen stock por una de la aplicación

![image](https://github.com/JoaqAb/rc-finalproject-resto-fe/assets/13739981/348638b7-dc9d-4443-b71d-0958b3a866ea)
