### ISSUE TITLE
Mesas

### ISSUE THREAD

**Issue by NicoGonzalez94** [JoaqAb/rc-finalproject-resto-fe#26]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que despues de elegir un numero de mesa no se muestre informacion por consola.

## Resultado actual

• Una vez enviado el numero de mesa elegido, se muestra informacion por consola.

## Captura

![image](https://github.com/JoaqAb/rc-finalproject-resto-fe/assets/166792979/852c7abc-90ba-4498-84d5-942cc3762408)
![image](https://github.com/JoaqAb/rc-finalproject-resto-fe/assets/166792979/a5f35822-63f4-4072-ad8a-50a87f837ee2)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by ramirokhouri** [comment]
eliminado el console.log en el navbar, lo que generaba que se muestre por consola la información
https://github.com/JoaqAb/rc-finalproject-resto-fe/commit/e24c92ef7c3d15d5c4f96d7ab0cc9c8203b482bf
