### ISSUE TITLE
Form contacto

### ISSUE THREAD

**Issue by NicoGonzalez94** [JoaqAb/rc-finalproject-resto-fe#28]
## Proceso

1. Ingrese a la pagina.
2. Quise hacer una consulta.

## Resultado esperado

• Que al hacer click en el boton enviar mi consulta se envié. 
• Encontrar un max de caracteres a colocar en el mensaje.
• Que no se muestre informacion por consola.

## Resultado actual

• Al hacer click en el boton de enviar mi consulta no se envía. 
• No se encuentra un max de caracteres a colocar en el mensaje.
• Al tratar de enviar la consulta o mensaje se muestra informacion por consola.

## Captura

![image](https://github.com/JoaqAb/rc-finalproject-resto-fe/assets/166792979/ad3ccec8-0971-4bf5-88c1-5ec3881af7de)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by ramirokhouri** [comment]
eliminados los console.log del componente Contact.jsx y campo de texto con maxLength={144}

respecto al envío del formulario, tanto el mensaje como una confirmación de envío del mismo llegan por mail

- la consulta

![image](https://github.com/JoaqAb/rc-finalproject-resto-fe/assets/13739981/9667e50b-cb3f-452d-86dc-0e9b28706c46)

- la confirmación

![image](https://github.com/JoaqAb/rc-finalproject-resto-fe/assets/13739981/c4d3d1c5-6b0e-42cb-8b1a-e6653ee4a162)

**Comment by ramirokhouri** [comment]
https://github.com/JoaqAb/rc-finalproject-resto-fe/commit/2bd461a1966f4db7dce2bc49c6277e25e4cfc09c

**Comment by LucasAlbarado** [comment]
Lo que llega al mail de restauranterolling1@gmail.com
![Rolling](https://github.com/JoaqAb/rc-finalproject-resto-fe/assets/126391773/267b3d79-c074-4881-bde9-a65e631c270b)
