### ISSUE TITLE
Registrarse

### ISSUE THREAD

**Issue by NicoGonzalez94** [JoaqAb/rc-finalproject-resto-fe#29]
## Proceso

1. Ingrese a la pagina.
2. Quise registrarme con un nuevo usuario.

## Resultado esperado

• Poder registrarme sin ningun problema.

## Resultado actual

• Al momento de completar el form de registro, por consola se puede ver informacion del registro. 

## Captura

[ [image]
](https://github.com/JoaqAb/rc-finalproject-resto-fe/assets/166792979/7e5d5951-b887-4633-a4cb-0d2de3c20582)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by ramirokhouri** [comment]
al registrarse ya no se exhiben los datos por consola
https://github.com/JoaqAb/rc-finalproject-resto-fe/commit/bce5ca2071b3fd1e493fab70ad912bbb34aef48b
