### ISSUE TITLE
Iniciar sesion

### ISSUE THREAD

**Issue by NicoGonzalez94** [JoaqAb/rc-finalproject-resto-fe#30]
## Proceso

1. Ingrese a la pagina.
2. Quise loguearme.

## Resultado esperado

• Que al iniciar sesion no se muestre informacion por consola.

## Resultado actual

• Al iniciar sesion con un usuario ya sea admin o cliente, se muestra informacion por consola.

## Captura

![image](https://github.com/JoaqAb/rc-finalproject-resto-fe/assets/166792979/904add75-be25-4936-b3cb-99dd914c774a)
![image](https://github.com/JoaqAb/rc-finalproject-resto-fe/assets/166792979/a8d022a1-fccb-4b43-85ff-3e1718a66e02)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by ramirokhouri** [comment]
al iniciar sesión ya no se muestran los datos por consola
